services:
  web:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - BACKEND_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /frontend/node_modules

  api:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coffee_tracker
      - DB_PORT=5432
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_tracker
    ports:
      - "5400:5432"
    volumes:
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
